language: go
go:
- 1.16.x
before_scripts:
scripts:
- go test -v ./...
before_deploy:
- touch .env
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: H4/f38FPM7u3+GiDRSYQ8vQwHlRCI4pfhOgTqxq0MuLI4VnqsBZnxtQ43MphyxM69BR5VeToA5yelljELlEIduV5P/n7AdguRGz5zr2brt3WrIyNlVZw+1zgQiTHw13hfoR48pHzNfkbv2VayaTQ+30yDPa1Ewx60PMGBY5yW4xH+dlN8n3ecw2z8JRLE2Xa+OK5uIicdqskCDSjhtCYKQsKPzigFBRRNwh/mev+QD9lcQ+6AuYiAQcVVCGYW21iqfyz0ii35hINlNLR0uMt4ogcC2bP1JLcB8/LFzGXwgoaXMm/AsUCrQZ7dwGtZ+6gGna4XxsBLrTDXEBqP0LfAIb4ribIyBh+cQoUJqYZmi+mHR3m9P69o0DWppVHt8XfzOy97U1PkqX3GfqytjfXU11O2h2bIUe5qicOXunFUEk7RUTHLtEkTTY7ph5dCQFJpsm9G7P4LZzJYbA9ckciI9qUadixfnrVJlUuMsNgno8l7NVf4r9MoxEpm66Fbkd95q/7fgr/bgtQJqb4wU0+C94Ws1JWuGk2Dr6jZwJlvbJ110hUDX0Z2XoEZKThXOazOTQBfdYcgXch+PHoTCRmZbpjC7Ovt0J+R1swMb2esibhmDD3Sy9u2hoe8dlb56rTGcwjoT99rrRukzPXb97q0gs7X0yR/gVeBReOJssLLMw=
  on: main
  app:
    main: ardafirdausr-discuss-server
