language: go
go:
- 1.16.x
before_scripts:
scripts:
- go test -v ./...
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: lvuwtygE7aNB5SnwmE5HLKxtsXRNkfCeYywLZX5KBSZbthWOjA0ZVP47kW5qQhpy3/ZuulHFiy8Uk70/4tM9B5R60a/VhfYmmOOTya/MpB0QaC3Yjo1SDaiqXlV/NXZPVpsEAKhq1mF64Gv/NF2GCj7Oeoo/leSTVMp4B+FtKnogGDulQn8XwSQ0MmO1/11+IaAZIHdf8EDksnSqRsGlvHJV3ZFPh8EfAUIJ9YgDPwhmfgLUMsYQRWmmz6z5DQUEBYM4DU7dhU08+DSEert+Y4eZ+sdizbbOFE8sjNj/FHMzDRXvTuj2SXDK4C6E6jg3DAkZHwUl3D+mz5PwCGAT7a0fDFV/MlKZc8AjqO0g9KgmLLtQ7yA2fIMBLGuXg4M50kzZnp6EDXvWMv7NtDJJ75DwmNIAQ6bXTZJc2Do2xAANM4KOVrik7pRvk3PRHrF2xXTgFA0VL5ZFgWDA5h6aOGKbjk8i6m7WruStFgK1uoFH0p3A41QZeGdQP20korXkxfQt0UN5kaJF+uBkBbfx1u1Rf/UAtEBnxFP6fp6JlidCe6kJkWxxnCxA0JDdpZn0Dx8mNduxiB3WMiqPHAWGpH/vT14e6FS4rRdMTw23Zwwj3oSPCzl2TESuhk3uW8LWuodcajsG+qJlRWhiu3PAnldkCUtEfPAPz4VGSUrJtMQ=
  on: main
  app:
    main: ardafirdausr-discuss-server
