name: Production CI/CD Pipeline

on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Specify your Go version here
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/discuss-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/discuss-server:${{ github.event.release.tag_name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Trigger Dokploy Deployment
        run: |
          curl -X 'POST' \
          'https://projects.ardafirdausr.com/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H 'x-api-key: ${{ secrets.DOKPLOY_APIKEY }}' \
          -H 'Content-Type: application/json' \
          -d '{
              "json":{
                  "applicationId": "${{ vars.APPLICATION_ID }}",
              }
          }'